"""capture_v2_schema_enhancements

Revision ID: cbb1d84cf989
Revises: 005_chunk_embeddings
Create Date: 2026-08-14 14:51:57.053287

"""
from collections.abc import Sequence

import alembic.op as op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cbb1d84cf989'
down_revision: str | Sequence[str] | None = '005_chunk_embeddings'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_items', sa.Column('structured_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('memory_items', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('memory_items', sa.Column('extraction_method', sa.String(length=50), nullable=True))
    op.add_column('memory_items', sa.Column('extraction_status', sa.String(length=30), nullable=True))
    op.add_column('memory_items', sa.Column('extraction_quality_score', sa.Float(), nullable=True))
    op.add_column('memory_items', sa.Column('extraction_quality_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('memory_items', sa.Column('raw_content_length', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('memory_items', sa.Column('received_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.create_index(op.f('ix_memory_items_content_hash'), 'memory_items', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_items_content_hash'), table_name='memory_items')
    op.drop_column('memory_items', 'received_at')
    op.drop_column('memory_items', 'raw_content_length')
    op.drop_column('memory_items', 'extraction_quality_reasons')
    op.drop_column('memory_items', 'extraction_quality_score')
    op.drop_column('memory_items', 'extraction_status')
    op.drop_column('memory_items', 'extraction_method')
    op.drop_column('memory_items', 'content_hash')
    op.drop_column('memory_items', 'structured_content')
    # ### end Alembic commands ###
